tree_species_word_clound = [{text: 'acer platanoides (spitzahorn)', size: 100},
{text: 'aesculus hippocastanum (rosskastanie)', size: 68},
{text: 'acer pseudoplatanus (bergahorn)', size: 51},
{text: 'fraxinus excelsior (gemeine esche)', size: 50},
{text: 'tilia cordata (winterlinde)', size: 50},
{text: 'platanus x acerifolia (ahornblättrige platane)', size: 44},
{text: 'robinia pseudoacacia (scheinakazie)', size: 41},
{text: 'tilia platyphyllos (sommerlinde)', size: 41},
{text: 'pinus nigra (schwarzkiefer, schwarzföhre)', size: 40},
{text: 'acer campestre (feldahorn)', size: 40},
{text: 'celtis australis (südlicher zürgelbaum)', size: 37},
{text: 'leerer pflanzstandort', size: 34},
{text: 'acer platanoides columnare (säulenahorn)', size: 32},
{text: 'populus nigra (schwarzpappel)', size: 31},
{text: 'betula pendula (weißbirke)', size: 31},
{text: 'sophora japonica (schnurbaum)', size: 31},
{text: 'pinus nigra nigra (österreichische schwarzkiefer)', size: 30},
{text: 'tilia spec. (linde)', size: 30},
{text: 'corylus colurna (baumhasel)', size: 29},
{text: 'carpinus betulus (hainbuche)', size: 28},
{text: 'populus nigra italica (pyramidenpappel)', size: 28},
{text: 'pyrus calleryana chanticleer (zierbirne)', size: 28},
{text: 'prunus avium (vogelkirsche)', size: 27},
{text: 'gleditsia triacanthos (lederhülsenbaum)', size: 27},
{text: 'quercus robur (stieleiche)', size: 27},
{text: 'aesculus x carnea (rotblühende kastanie)', size: 27},
{text: 'fraxinus ornus (blumenesche)', size: 26},
{text: 'tilia cordata rancho (kleinblättrige winterlinde)', size: 26},
{text: 'tilia cordata greenspire (stadtlinde)', size: 26},
{text: 'juglans regia (walnussbaum)', size: 25},
{text: 'prunus serrulata kanzan (japanische blütenkirsche)', size: 25},
{text: 'carpinus betulus fastigiata (säulenhainbuche)', size: 25},
{text: 'carpinus betulus frans fontaine (schlanke säulenhainbuche)', size: 24},
{text: 'ailanthus altissima (götterbaum)', size: 24},
{text: 'populus alba (silberpappel)', size: 24},
{text: 'taxus baccata (heimische eibe)', size: 24},
{text: 'prunus cerasifera nigra (blutpflaume)', size: 24},
{text: 'koelreuteria paniculata (blasenbaum)', size: 24},
{text: 'acer platanoides globosum (kugelspitzahorn)', size: 23},
{text: 'acer campestre elsrijk (feldahorn)', size: 23},
{text: 'acer negundo (eschenahorn)', size: 23},
{text: 'acer platanoides eurostar (spitzahorn)', size: 23},
{text: 'tilia tomentosa (silberlinde)', size: 23},
{text: 'acer platanoides crimson king (blutahorn)', size: 23},
{text: 'celtis occidentalis (westlicher zürgelbaum)', size: 22},
{text: 'prunus cerasifera (kirschpflaume)', size: 22},
{text: 'fraxinus ornus obelisk (säulenblumenesche)', size: 22},
{text: 'gleditsia triacanthos skyline (säulengleditschie)', size: 22},
{text: 'malus spec. (apfelbaum)', size: 22},
{text: 'picea abies (gemeine fichte)', size: 22},
{text: 'populus x canadensis (kanadische pappel)', size: 22},
{text: 'prunus spec. (kirsche)', size: 22},
{text: 'populus x canescens (graupappel)', size: 22},
{text: 'catalpa bignonioides (trompetenbaum)', size: 21},
{text: 'ginkgo biloba (fächerblattbaum)', size: 21},
{text: 'fraxinus excelsior altena (gemeine esche)', size: 21},
{text: 'platanus spec. (platane)', size: 21},
{text: 'fraxinus excelsior diversifolia (einblättrige esche)', size: 21},
{text: 'tilia x vulgaris (holländische linde)', size: 21},
{text: 'tilia x europaea pallida (kaiserlinde)', size: 21},
{text: 'ulmus spec. (ulme)', size: 21},
{text: 'tilia x euchlora (krimlinde)', size: 21},
{text: 'fraxinus excelsior globosa (kugelesche)', size: 21},
{text: 'acer pseudoplatanus atropurpureum (purpurner bergahorn)', size: 21},
{text: 'quercus robur fastigiata (säuleneiche)', size: 21},
{text: 'prunus serrulata amanogawa (säulenkirsche)', size: 20},
{text: 'paulownia tomentosa (blauglockenbaum)', size: 20},
{text: 'ulmus minor (feldulme)', size: 20},
{text: 'quercus cerris (zerreiche)', size: 20},
{text: 'fagus sylvatica (rotbuche)', size: 20},
{text: 'robinia pseudoacacia monophylla (straßenakazie)', size: 20},
{text: 'tilia tomentosa brabant (silberlinde)', size: 20},
{text: 'populus simonii (birkenpappel)', size: 20},
{text: 'pinus sylvestris (gemeine kiefer)', size: 20},
{text: 'picea pungens glauca (blaufichte)', size: 20},
{text: 'fraxinus spec. (esche)', size: 20},
{text: 'populus spec. (pappel)', size: 20},
{text: 'aesculus x carnea briotii (scharlachkastanie)', size: 20},
{text: 'prunus padus (traubenkirsche)', size: 20},
{text: 'fraxinus pennsylvanica (rotesche)', size: 20},
{text: 'salix alba (silberweide)', size: 20},
{text: 'koelreuteria paniculata fastigiata (säulenblasenbaum)', size: 20},
{text: 'sambucus nigra (schwarzer holunder)', size: 20},
{text: 'fraxinus excelsior westhofs glorie (esche)', size: 20},
{text: 'acer platanoides cleveland (kegelspitzahorn)', size: 20},
{text: 'fraxinus ornus meczek (kugelblumenesche)', size: 20},
{text: 'acer saccharinum (silberahorn)', size: 20},
{text: 'morus alba (weißer maulbeerbaum)', size: 20},
{text: 'gymnocladus dioicus (geweihbaum)', size: 20},
{text: 'pyrus calleryana aristocrat (zierbirne)', size: 20},
{text: 'fraxinus excelsior atlas (gemeine esche)', size: 20},
{text: 'ulmus glabra (bergulme)', size: 20},
{text: 'platanus x acerifolia tremonia (schmalkronige platane)', size: 20},
{text: 'quercus spec. (eiche)', size: 20},
{text: 'tilia americana (amerikanische linde)', size: 20},
{text: 'platanus orientalis minaret (orientalische säulenplatane)', size: 20},
{text: 'ulmus new horizon (resista ulme)', size: 20},
{text: 'gleditsia triacanthos inermis (dornenloser lederhülsenbaum)', size: 20},
{text: 'acer platanoides schwedleri (rotblättriger spitzahorn)', size: 20},
{text: 'carpinus betulus columnaris (pyramidenhainbuche)', size: 20}
];
